# Install node
FROM node:18 as build

# Install FFMPEG library
RUN apt update -y
RUN apt install ffmpeg -y

# Set the workdir /app
WORKDIR /app

# Frontend
# Copy the package.json to workdir
COPY package.json ./
COPY server/package.json ./server/

# Install dependncies
RUN npm install --legacy-peer-deps --loglevel verbose

# Copy application source
COPY . .

EXPOSE 4000

# run express server
# RUN node server/index.js
CMD ["npm", "run", "prd"]
