# Install node
FROM node:18

# Install FFMPEG library
RUN apt update -y
RUN apt install ffmpeg -y

# Set the workdir /app
WORKDIR /app

# Frontend
# Copy the package.json to workdir
COPY package.json .
COPY package-lock.json .
COPY index.html .
COPY vite.config.js .
COPY server/package.json ./server/
COPY server/package-lock.json ./server

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

RUN npm ci --legacy-peer-deps --loglevel verbose

EXPOSE 3000 4000

# Start the application
CMD ["npm", "run", "dev"]
